// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package SmartOffice.service2;

public interface BookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.BookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room_id = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string room_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();

  /**
   * <code>string user_id = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string start_time = 3;</code>
   */
  java.lang.String getStartTime();
  /**
   * <code>string start_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getStartTimeBytes();

  /**
   * <code>string end_time = 4;</code>
   */
  java.lang.String getEndTime();
  /**
   * <code>string end_time = 4;</code>
   */
  com.google.protobuf.ByteString
      getEndTimeBytes();
}
