// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package SmartOffice.service2;

public interface RoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.RoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string floor = 1;</code>
   */
  java.lang.String getFloor();
  /**
   * <code>string floor = 1;</code>
   */
  com.google.protobuf.ByteString
      getFloorBytes();
}
