// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package SmartOffice.service2;

public interface RoomListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.RoomList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .service2.Room rooms = 1;</code>
   */
  java.util.List<SmartOffice.service2.Room> 
      getRoomsList();
  /**
   * <code>repeated .service2.Room rooms = 1;</code>
   */
  SmartOffice.service2.Room getRooms(int index);
  /**
   * <code>repeated .service2.Room rooms = 1;</code>
   */
  int getRoomsCount();
  /**
   * <code>repeated .service2.Room rooms = 1;</code>
   */
  java.util.List<? extends SmartOffice.service2.RoomOrBuilder> 
      getRoomsOrBuilderList();
  /**
   * <code>repeated .service2.Room rooms = 1;</code>
   */
  SmartOffice.service2.RoomOrBuilder getRoomsOrBuilder(
      int index);
}
