// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package SmartOffice.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_RoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_RoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Room_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Room_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_RoomList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_RoomList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_BookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_BookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_BookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_BookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_CancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_CancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_CancelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_CancelResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\"\034\n\013RoomReques" +
      "t\022\r\n\005floor\030\001 \001(\t\"8\n\004Room\022\017\n\007room_id\030\001 \001(" +
      "\t\022\014\n\004name\030\002 \001(\t\022\021\n\tavailable\030\003 \001(\010\")\n\010Ro" +
      "omList\022\035\n\005rooms\030\001 \003(\0132\016.service2.Room\"U\n" +
      "\013BookRequest\022\017\n\007room_id\030\001 \001(\t\022\017\n\007user_id" +
      "\030\002 \001(\t\022\022\n\nstart_time\030\003 \001(\t\022\020\n\010end_time\030\004" +
      " \001(\t\"\037\n\014BookResponse\022\017\n\007success\030\001 \001(\010\"1\n" +
      "\rCancelRequest\022\017\n\007room_id\030\001 \001(\t\022\017\n\007user_" +
      "id\030\002 \001(\t\"!\n\016CancelResponse\022\017\n\007success\030\001 " +
      "\001(\0102\322\001\n\010Service2\022@\n\021GetAvailableRooms\022\025." +
      "service2.RoomRequest\032\022.service2.RoomList" +
      "\"\000\022=\n\010BookRoom\022\025.service2.BookRequest\032\026." +
      "service2.BookResponse\"\0000\001\022E\n\nCancelRoom\022" +
      "\027.service2.CancelRequest\032\030.service2.Canc" +
      "elResponse\"\000(\0010\001B&\n\024SmartOffice.service2" +
      "B\014Service2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_RoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_RoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_RoomRequest_descriptor,
        new java.lang.String[] { "Floor", });
    internal_static_service2_Room_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_Room_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Room_descriptor,
        new java.lang.String[] { "RoomId", "Name", "Available", });
    internal_static_service2_RoomList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_RoomList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_RoomList_descriptor,
        new java.lang.String[] { "Rooms", });
    internal_static_service2_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_BookRequest_descriptor,
        new java.lang.String[] { "RoomId", "UserId", "StartTime", "EndTime", });
    internal_static_service2_BookResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service2_BookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_BookResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_service2_CancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service2_CancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_CancelRequest_descriptor,
        new java.lang.String[] { "RoomId", "UserId", });
    internal_static_service2_CancelResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_service2_CancelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_CancelResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
