// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package SmartOffice.service3;

public interface CheckInResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.CheckInResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string check_in_time = 2;</code>
   */
  java.lang.String getCheckInTime();
  /**
   * <code>string check_in_time = 2;</code>
   */
  com.google.protobuf.ByteString
      getCheckInTimeBytes();
}
