// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package SmartOffice.service3;

public interface CheckOutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.CheckOutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employee_id = 1;</code>
   */
  java.lang.String getEmployeeId();
  /**
   * <code>string employee_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeIdBytes();
}
