// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package SmartOffice.service3;

public interface CheckOutResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.CheckOutResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string check_out_time = 2;</code>
   */
  java.lang.String getCheckOutTime();
  /**
   * <code>string check_out_time = 2;</code>
   */
  com.google.protobuf.ByteString
      getCheckOutTimeBytes();
}
