// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package SmartOffice.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_CheckInRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_CheckInRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_CheckInResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_CheckInResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_CheckOutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_CheckOutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_CheckOutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_CheckOutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\032\033google/proto" +
      "buf/empty.proto\032\037google/protobuf/timesta" +
      "mp.proto\"%\n\016CheckInRequest\022\023\n\013employee_i" +
      "d\030\001 \001(\t\"9\n\017CheckInResponse\022\017\n\007message\030\001 " +
      "\001(\t\022\025\n\rcheck_in_time\030\002 \001(\t\"&\n\017CheckOutRe" +
      "quest\022\023\n\013employee_id\030\001 \001(\t\";\n\020CheckOutRe" +
      "sponse\022\017\n\007message\030\001 \001(\t\022\026\n\016check_out_tim" +
      "e\030\002 \001(\t2\221\001\n\010Service3\022@\n\007checkIn\022\030.servic" +
      "e3.CheckInRequest\032\031.service3.CheckInResp" +
      "onse\"\000\022C\n\010checkOut\022\031.service3.CheckOutRe" +
      "quest\032\032.service3.CheckOutResponse\"\000B&\n\024S" +
      "martOffice.service3B\014Service3ImplP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_service3_CheckInRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_CheckInRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_CheckInRequest_descriptor,
        new java.lang.String[] { "EmployeeId", });
    internal_static_service3_CheckInResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_CheckInResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_CheckInResponse_descriptor,
        new java.lang.String[] { "Message", "CheckInTime", });
    internal_static_service3_CheckOutRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_CheckOutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_CheckOutRequest_descriptor,
        new java.lang.String[] { "EmployeeId", });
    internal_static_service3_CheckOutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_CheckOutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_CheckOutResponse_descriptor,
        new java.lang.String[] { "Message", "CheckOutTime", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
