// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package SmartOffice.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TurnOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TurnOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TurnOnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TurnOnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TurnOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TurnOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TurnOffResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TurnOffResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_SetBrightnessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_SetBrightnessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_SetBrightnessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_SetBrightnessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"1\n\rTurnOnRequ" +
      "est\022\017\n\007room_id\030\001 \001(\t\022\017\n\007turn_on\030\002 \001(\010\"!\n" +
      "\016TurnOnResponse\022\017\n\007success\030\001 \001(\010\"3\n\016Turn" +
      "OffRequest\022\017\n\007room_id\030\001 \001(\t\022\020\n\010turn_off\030" +
      "\002 \001(\010\"\"\n\017TurnOffResponse\022\017\n\007success\030\001 \001(" +
      "\010\"?\n\024SetBrightnessRequest\022\017\n\007room_id\030\001 \001" +
      "(\t\022\026\n\016set_brightness\030\002 \001(\t\"(\n\025SetBrightn" +
      "essResponse\022\017\n\007success\030\001 \001(\0102\345\001\n\010Service" +
      "1\022?\n\010ToggleOn\022\027.service1.TurnOnRequest\032\030" +
      ".service1.TurnOnResponse\"\000\022B\n\tToggleOff\022" +
      "\030.service1.TurnOffRequest\032\031.service1.Tur" +
      "nOffResponse\"\000\022T\n\rSerBrightness\022\036.servic" +
      "e1.SetBrightnessRequest\032\037.service1.SetBr" +
      "ightnessResponse\"\000(\001B&\n\024SmartOffice.serv" +
      "ice1B\014Service1ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_TurnOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_TurnOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TurnOnRequest_descriptor,
        new java.lang.String[] { "RoomId", "TurnOn", });
    internal_static_service1_TurnOnResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_TurnOnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TurnOnResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_service1_TurnOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_TurnOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TurnOffRequest_descriptor,
        new java.lang.String[] { "RoomId", "TurnOff", });
    internal_static_service1_TurnOffResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_TurnOffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TurnOffResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_service1_SetBrightnessRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_SetBrightnessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_SetBrightnessRequest_descriptor,
        new java.lang.String[] { "RoomId", "SetBrightness", });
    internal_static_service1_SetBrightnessResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_SetBrightnessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_SetBrightnessResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
