// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package SmartOffice.service1;

public interface SetBrightnessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.SetBrightnessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room_id = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string room_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();

  /**
   * <code>string set_brightness = 2;</code>
   */
  java.lang.String getSetBrightness();
  /**
   * <code>string set_brightness = 2;</code>
   */
  com.google.protobuf.ByteString
      getSetBrightnessBytes();
}
