// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package SmartOffice.service1;

public interface TurnOffResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.TurnOffResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
