// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package SmartOffice.service1;

public interface TurnOffRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.TurnOffRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string room_id = 1;</code>
   */
  java.lang.String getRoomId();
  /**
   * <code>string room_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomIdBytes();

  /**
   * <code>bool turn_off = 2;</code>
   */
  boolean getTurnOff();
}
